-- Add pet system fields to pisunchik_data table
ALTER TABLE pisunchik_data
ADD COLUMN IF NOT EXISTS pet JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pet_titles JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS pet_active_title VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pet_revives_used INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pet_revives_reset_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS trivia_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_trivia_date TIMESTAMP WITH TIME ZONE DEFAULT NULL;
