-- Add hunger/happiness/ulta fields to pisunchik_data table
ALTER TABLE pisunchik_data
ADD COLUMN IF NOT EXISTS pet_hunger INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS pet_happiness INTEGER DEFAULT 50,
ADD COLUMN IF NOT EXISTS pet_hunger_last_decay TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pet_happiness_last_activity TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pet_ulta_used_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pet_ulta_free_roll_pending BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pet_ulta_oracle_pending BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pet_ulta_trivia_pending BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pet_casino_extra_spins INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pet_ulta_oracle_preview JSONB DEFAULT NULL;
